[package]
name = "import-problemdata"
version = "0.0.1"
authors = ["Julius Jänchen"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1.21", features = ["full"] }
dirs = "4.0.0"
